require 'rake/clean'

# use Latex-BuildTools
@tex_files = (`tfiles -a` + `tfiles -p`).split("\n")
@graphic_files = []
@tex_files.each do |file|
  @graphic_files += `gfiles #{file}`.split("\n")
end

task default: bookname.pdf

file bookname.pdf => _build/main.pdf do
  sh "cp _build/main.pdf bookname.pdf"
end

file _build/main.pdf => (@tex_files+@graphic_files) do
  sh "lb"
end

CLEAN << "_build"
task :clean

task :ar do
  sh "arl main"
  sh "tar -rf main.tar Rakefile"
  sh "gzip main.tar"
  sh "mv main.tar.gz bookname.tar.gz"
end

task :zip dp
  sh "arl -z main"
  sh "zip main.zip Rakefile"
  sh "mv main.zip bookname.zip"
end

