require 'rake/clean'

# if readme.tex doesn't exist, generate it first.
# This is necessary because readme.tex is accessed by gfiles in
#  line 12.
if File.exist?("readme.tex") == false
  sh "pandoc -o readme.tex ../Readme.md"
end
# use Latex-BuildTools
@tex_files = (`tfiles -a` + `tfiles -p`).split("\n")
@tex_files <<= "readme.tex"
@graphic_files = []
@tex_files.each do |file|
  @graphic_files += `gfiles #{file}`.split("\n")
end

task default: "チュートリアル.pdf"

file "チュートリアル.pdf" => "_build/main.pdf" do
  sh "cp _build/main.pdf チュートリアル.pdf"
end

file "_build/main.pdf" => (@tex_files+@graphic_files) do
  sh "lb main.tex"
end

file "readme.tex" => "../Readme.ja.md" do
  sh "pandoc -o readme.tex ../Readme.ja.md"
end

CLEAN << "_build"
task :clean

task :ar do
  sh "arl main.tex"
  sh "tar -rf main.tar Rakefile"
  sh "gzip main.tar"
  sh "mv main.tar.gz チュートリアル.tar.gz"
end

task :zip do
  sh "arl -z main.tex"
  sh "zip main.zip Rakefile"
  sh "mv main.zip チュートリアル.zip"
end
